{{- if .Values.components.mcpGateway.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: mcp-gateway
  namespace: "{{ .Values.mcpGateway.namespaces.gatewaySystem }}"
  annotations:
    networking.istio.io/service-type: ClusterIP
  labels:
    gateway-type: mcpgateway
    istio: ingressgateway
spec:
  gatewayClassName: istio
  listeners:
    - name: mcp # going to the Broker, and no hostname field
      port: 8080
      protocol: HTTP
      allowedRoutes:
        namespaces:
          from: All
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  namespace: "{{ .Values.mcpGateway.namespaces.mcpSystem }}"
  name: mcp-route
  annotations:
    "helm.sh/hook": post-install, post-upgrade
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  parentRefs:
    - name: mcp-gateway
      namespace: "{{ .Values.mcpGateway.namespaces.gatewaySystem }}"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /mcp
      backendRefs:
        - name: mcp-gateway-broker
          port: 8080
---          
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: mcp-gateway
  namespace: "{{ .Values.mcpGateway.namespaces.gatewaySystem }}"
spec:
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  port:
    targetPort: mcp
  to:
    kind: Service
    name: mcp-gateway-istio
    weight: 100
  wildcardPolicy: None
---
# TODO - verify if this service required in stand-alone install of mcp-gateway chart
apiVersion: v1
kind: Service
metadata:
  name: mcp-broker
  namespace:  "{{ .Values.mcpGateway.namespaces.mcpSystem }}"
  labels:
    component: broker
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/instance: kagenti
    app.kubernetes.io/name: mcp-gateway
    component: broker-router
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
    - name: grpc
      port: 50051
      targetPort: 50051
      protocol: TCP
---
# TODO - verify if this service required in stand-alone install of mcp-gateway chart
apiVersion: v1
kind: Service
metadata:
  name: mcp-config
  namespace:  "{{ .Values.mcpGateway.namespaces.mcpSystem }}"
  labels:
    component: config-api
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/instance: kagenti
    app.kubernetes.io/name: mcp-gateway
    component: broker-router
  ports:
    - name: http
      port: 8181
      targetPort: 8181
      protocol: TCP
{{- end }}
